.catalog:
    name: "Convoy EFS"
    version: "v0.2.0"
    description: "Convoy EFS - Docker volume plugin"
    questions:
     - variable: "EFS_SERVER"
       description: "DNS name of AWS EFS"
       label: "EFS Server"
       required: true
       type: "string"
     - variable: "MOUNT_DIR"
       label: "Mount Directory"
       description: "The directory on the EFS server to mount"
       type: "string"
       required: true

convoy-efs:
    metadata:
        efs_server: "${EFS_SERVER}"
        mount_dir: "${MOUNT_DIR}"
        mount_opts: "${MOUNT_OPTS}"
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10241
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

convoy-efs-storagepool:
    metadata:
        efs_server: "${EFS_SERVER}"
        mount_dir: "${MOUNT_DIR}"
        mount_opts: "${MOUNT_OPTS}"
    scale: 1
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10241
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
